# Generated by Django 4.2.3 on 2023-07-20 06:21

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('birthday', models.IntegerField()),
                ('nickname', models.CharField(max_length=20)),
                ('gender', models.IntegerField()),
                ('age_range', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'account',
            },
            managers=[
                ('objects', account.models.FunSunUserManager()),
            ],
        ),
    ]
