# Generated by Django 4.2.3 on 2023-07-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(max_length=6),
        ),
    ]
