# Generated by Django 4.2.3 on 2023-07-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_birthday_alter_account_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='nickname',
            new_name='username',
        ),
    ]
