# Generated by Django 4.2.3 on 2023-08-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank_account',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
