# Generated by Django 4.2.3 on 2024-02-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_age_range_alter_account_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='followee_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
    ]
