# Generated by Django 4.2.3 on 2023-07-26 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Remit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Remit', to=settings.AUTH_USER_MODEL)),
                ('funding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Remit', to='funding.funding')),
            ],
        ),
    ]
