# Generated by Django 4.2.3 on 2024-02-07 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0004_alter_funding_expire_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('remit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remit',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='remit',
            name='funding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remit', to='funding.funding'),
        ),
    ]
