# Generated by Django 4.2.3 on 2024-02-08 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funding', '0007_alter_funding_expire_on'),
        ('remit', '0002_alter_remit_author_alter_remit_funding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remit',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remit_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='remit',
            name='funding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remit_funding', to='funding.funding'),
        ),
    ]
