version: "0.1"
services:
  sample-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: funsun-server
    volumes:
      - ./app/:/app
    ports:
      - "80:80"
      - "8080:8080"
    restart: always