# Generated by Django 4.2.3 on 2023-07-26 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funding',
            name='img',
        ),
        migrations.AddField(
            model_name='funding',
            name='expire_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funding',
            name='image',
            field=models.ImageField(null=True, upload_to='funding_image/'),
        ),
    ]
