# Generated by Django 4.2.3 on 2023-08-06 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 14, 35, 37, 325244, tzinfo=datetime.timezone.utc)),
        ),
    ]
