# Generated by Django 4.2.3 on 2023-08-06 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0002_alter_funding_expire_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 14, 39, 8, 222535, tzinfo=datetime.timezone.utc)),
        ),
    ]
