# Generated by Django 4.2.3 on 2023-07-26 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0002_remove_funding_img_funding_expire_on_funding_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 9, 25, 53, 950627, tzinfo=datetime.timezone.utc)),
        ),
    ]
