# Generated by Django 4.2.3 on 2024-02-07 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0003_alter_funding_expire_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 8, 5, 44, 34, 60935, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddIndex(
            model_name='funding',
            index=models.Index(fields=['id'], name='funding_fun_id_f1c158_idx'),
        ),
        migrations.AddIndex(
            model_name='funding',
            index=models.Index(fields=['author'], name='funding_fun_author__083751_idx'),
        ),
    ]
