# Generated by Django 4.2.3 on 2023-07-29 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0004_funding_is_transmitted_alter_funding_expire_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 7, 51, 32, 845934, tzinfo=datetime.timezone.utc)),
        ),
    ]
