# Generated by Django 4.2.3 on 2024-02-07 06:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funding', '0004_alter_funding_expire_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='funding',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 8, 6, 20, 28, 302720, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='funding',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
