# Generated by Django 4.2.3 on 2023-07-29 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0005_alter_funding_expire_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 7, 56, 19, 88143, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='funding',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
