# Generated by Django 4.2.3 on 2024-02-07 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0005_alter_funding_author_alter_funding_expire_on_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='funding',
            name='funding_fun_id_f1c158_idx',
        ),
        migrations.RemoveIndex(
            model_name='funding',
            name='funding_fun_author__083751_idx',
        ),
        migrations.AlterField(
            model_name='funding',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 8, 6, 24, 0, 963209, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='funding',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
