# Generated by Django 4.2.3 on 2024-02-08 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0006_remove_funding_funding_fun_id_f1c158_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 9, 4, 59, 27, 582885, tzinfo=datetime.timezone.utc)),
        ),
    ]
