# Generated by Django 4.2.3 on 2023-07-31 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0006_alter_funding_expire_on_alter_funding_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='review',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='funding',
            name='review_image',
            field=models.ImageField(null=True, upload_to='review_image/'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 6, 20, 48, 610575, tzinfo=datetime.timezone.utc)),
        ),
    ]
