# Generated by Django 4.2.3 on 2023-08-06 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0007_funding_review_funding_review_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 12, 34, 31, 271314, tzinfo=datetime.timezone.utc)),
        ),
    ]
