# Generated by Django 4.2.3 on 2024-02-08 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0007_alter_funding_expire_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 9, 5, 12, 48, 328470, tzinfo=datetime.timezone.utc)),
        ),
    ]
