# Generated by Django 4.2.3 on 2024-02-09 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0009_alter_funding_expire_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 10, 6, 17, 17, 746089, tzinfo=datetime.timezone.utc)),
        ),
    ]
