# Generated by Django 4.2.3 on 2024-02-10 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0010_alter_funding_expire_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 11, 0, 6, 8, 343659, tzinfo=datetime.timezone.utc)),
        ),
    ]
